export const SET_LOADING = "SET_LOADING";
export const GET_LOADING = "GET_LOADING";
export const SET_PROJECTS = "SET_PROJECTS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
